runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /javascript
  static_dir: javascript
- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
