runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /js
  static_dir: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
